### ISSUE TITLE
delay and reverb are global?

### ISSUE THREAD

**Issue by okyeron** [schollz/pitter-patter#8]
delay and reverb send amounts for each sequence affect all other sequences as well.

should they be separate?

The amounts in params show different values, but it seems only one is having an effect.

**Comment by schollz** [comment]
oh yeah this is a holdover from how I implemented the supercollider stuff - the effect sends are per instrument not per voice. I'll leave this open, its a big change unfortunately.

**Comment by schollz** [comment]
should be fixed now!
